
sonar.projectKey=TuukkaUusitalo_proj_course_2_week_3
sonar.organization=tuukkauusitalo

sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.token=${env.SONAR_TOKEN}